# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 Alyssa Ross <hi@alyssa.is>
---
title: Spectrum Docs
theme: just-the-docs
aux_links:
  Home:
    - "https://spectrum-os.org/"
  Git:
    - "https://spectrum-os.org/git/"
  Lists:
    - "https://spectrum-os.org/lists/"
plugins:
  - jekyll-asciidoc
exclude:
  - '*.license'
  - '*.nix'
  - result*
asciidoctor:
  attributes:
    showtitle: '@'
    source-highlighter: rouge
